In [15]:
import tensorflow_datasets as tfds

#load the IMDB Reviews dataset
imdb, info = tfds.load("imdb_reviews", with_info=True, as_supervised=True)

In [16]:
print(info)

tfds.core.DatasetInfo(
    name='imdb_reviews',
    version=1.0.0,
    description='Large Movie Review Dataset.
This is a dataset for binary sentiment classification containing substantially more data than previous benchmark datasets. We provide a set of 25,000 highly polar movie reviews for training, and 25,000 for testing. There is additional unlabeled data for use as well.',
    homepage='http://ai.stanford.edu/~amaas/data/sentiment/',
    features=FeaturesDict({
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
        'text': Text(shape=(), dtype=tf.string),
    }),
    total_num_examples=100000,
    splits={
        'test': 25000,
        'train': 25000,
        'unsupervised': 50000,
    },
    supervised_keys=('text', 'label'),
    citation="""@InProceedings{maas-EtAl:2011:ACL-HLT2011,
      author    = {Maas, Andrew L.  and  Daly, Raymond E.  and  Pham, Peter T.  and  Huang, Dan  and  Ng, Andrew Y.  and  Potts, Christopher},
      title     = {Learning Word

As you can see in the output above, there is a total of 100,000 examples in the dataset and it is split into `train`, `test` and `unsupervised` sets. For this lab, you will only use `train` and `test` sets because you will need labeled examples to train your model.

## Split the dataset

If you try printing the `imdb` dataset that you downloaded earlier, you will see that it contains the dictionary that points to [`tf.data.Dataset`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) objects. You will explore more of this class and its API in Course 4 of this specialization. For now, you can just think of it as a collection of examples.

In [17]:
#print the contents of the dataset you downloaded
print(imdb)

{'test': <PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>, 'train': <PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>, 'unsupervised': <PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>}


In [18]:
#Preview the raw format of a few examples using the take() method
for example in imdb['train'].take(2):
  print(example)

(<tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on

You can see that each example is a 2-element tuple of tensors containing the text first, then the label 

The next cell below will take the train and test sentences and labels into separate lists so you can preprocess the text and feed it to the model later

In [19]:
import numpy as np 

#get the train and test sets
train_data, test_data = imdb['train'], imdb['test']

#initialize the sentences and labels lists
training_sentences = []
training_labels = []

testing_sentences = []
testing_labels = []

#loop over all training examples and save the sentences and labels 
for s,l in train_data:
  training_sentences.append(s.numpy().decode('utf8'))
  training_labels.append(l.numpy())

#loop over all testing examples and save the sentences and labels 
for s,l in test_data:
  testing_sentences.append(s.numpy().decode('utf8'))
  testing_labels.append(l.numpy())

#Convert labels lists to numpy array 
training_labels_final = np.array(training_labels)
testing_labels_final = np.array(testing_labels)

##Generate Padded Sequences 

Now you can do the text preprocessing steps you've learned last week. You will tokenize the sentences and pad them to a uniform length. 

We've separated the parameters into its own code cell below so it will be easy for you to tweak it later if you want 

In [40]:
#Parameters 

vocab_size = 10000
max_length = 120
embedding_dim = 16
trunc_type = 'post'
oov_tok = '<OOV>'

In [41]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Initialize the Tokenizer class
tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)

# Generate the word index dictionary for the training sentences
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index
#
# Generate and pad the training sequences
sequences = tokenizer.texts_to_sequences(training_sentences)
padded = pad_sequences(sequences,maxlen=max_length, truncating=trunc_type)

# Generate and pad the test sequences
testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences,maxlen=max_length)


## Build and Compile the Model

With the data already preprocessed, you can proceed to building your sentiment classification model. The input will be an [`Embedding`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding) layer. The main idea here is to represent each word in your vocabulary with vectors. These vectors have trainable weights so as your neural network learns, words that are most likely to appear in a positive tweet will converge towards similar weights. Similarly, words in negative tweets will be clustered more closely together. You can read more about word embeddings [here](https://www.tensorflow.org/text/guide/word_embeddings).

After the `Embedding` layer, you will flatten its output and feed it into a `Dense` layer. You will explore other architectures for these hidden layers in the next labs.

The output layer would be a single neuron with a sigmoid activation to distinguish between the 2 classes. As is typical with binary classifiers, you will use the `binary_crossentropy` as your loss function while training.

In [50]:
import tensorflow as tf

#Build the model 

model = tf.keras.Sequential([
                             tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length = max_length),
                             tf.keras.layers.Flatten(),
                             tf.keras.layers.Dense(6, activation = 'relu'),
                             tf.keras.layers.Dense(1, activation = 'sigmoid')
])

#Setup the training parameters
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 120, 16)           160000    
                                                                 
 flatten_5 (Flatten)         (None, 1920)              0         
                                                                 
 dense_10 (Dense)            (None, 6)                 11526     
                                                                 
 dense_11 (Dense)            (None, 1)                 7         
                                                                 
Total params: 171,533
Trainable params: 171,533
Non-trainable params: 0
_________________________________________________________________


##Train The Model 

Next of course is training the model. With current settings, you'll get a near perfect training accuracy after 5 epochs. However, the validation accuracy will plateau at around 83%

I made edits to the vocab_size by making it 10,000 instead of 1,000 and to the number of Dense neurons making it 24 instead of 6

In [51]:
num_epochs = 10

model.fit(padded, training_labels_final, epochs = num_epochs, validation_data = (testing_padded, testing_labels_final))

Epoch 1/10
782/782 [==============================] - 6s 7ms/step - loss: 0.4996 - accuracy: 0.7347 - val_loss: 0.3470 - val_accuracy: 0.8467
Epoch 2/10
782/782 [==============================] - 6s 7ms/step - loss: 0.2308 - accuracy: 0.9105 - val_loss: 0.3701 - val_accuracy: 0.8394
Epoch 3/10
782/782 [==============================] - 5s 7ms/step - loss: 0.0737 - accuracy: 0.9834 - val_loss: 0.4602 - val_accuracy: 0.8254
Epoch 4/10
782/782 [==============================] - 5s 7ms/step - loss: 0.0155 - accuracy: 0.9983 - val_loss: 0.5452 - val_accuracy: 0.8223
Epoch 5/10
782/782 [==============================] - 5s 6ms/step - loss: 0.0038 - accuracy: 0.9999 - val_loss: 0.5839 - val_accuracy: 0.8286
Epoch 6/10
782/782 [==============================] - 5s 7ms/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 0.6274 - val_accuracy: 0.8283
Epoch 7/10
782/782 [==============================] - 5s 7ms/step - loss: 7.3016e-04 - accuracy: 1.0000 - val_loss: 0.6669 - val_accuracy: 0.8289
Ep

## Visualize Word Embeddings

After training, you can visualize the trained weights in the `Embedding` layer to see words that are clustered together. The [Tensorflow Embedding Projector](https://projector.tensorflow.org/) is able to reduce the 16-dimension vectors you defined earlier into fewer components so it can be plotted in the projector. First, you will need to get these weights and you can do that with the cell below:

In [52]:
#Get the embedding layer from the model (first layer)
embedding_layer = model.layers[0]

#Get the weights of the embedding layer 
embedding_weights = embedding_layer.get_weights()[0]

#print the shape 
#Expected is (vocab_size, embedding_dim)
print(embedding_weights.shape)

(10000, 16)


You will need to generate two files:

* `vecs.tsv` - contains the vector weights of each word in the vocabulary
* `meta.tsv` - contains the words in the vocabulary

For this, it is useful to have `reverse_word_index` dictionary so you can quickly lookup a word based on a given index. For example, `reverse_word_index[1]` will return your OOV token because it is always at index = 1. Fortunately, the `Tokenizer` class already provides this dictionary through its `index_word` property. Yes, as the name implies, it is the reverse of the `word_index` property which you used earlier!

In [53]:
#Get the index-word dictionary (reverse of word-index)
reverse_word_index = tokenizer.index_word


In [54]:
import io

# Open writeable files
out_v = io.open('vecs.tsv', 'w', encoding='utf-8')
out_m = io.open('meta.tsv', 'w', encoding='utf-8')

# Initialize the loop. Start counting at `1` because `0` is just for the padding
for word_num in range(1, vocab_size):

  # Get the word associated at the current index
  word_name = reverse_word_index[word_num]

  # Get the embedding weights associated with the current index
  word_embedding = embedding_weights[word_num]

  # Write the word name
  out_m.write(word_name + "\n")

  # Write the word embedding
  out_v.write('\t'.join([str(x) for x in word_embedding]) + "\n")

# Close the files
out_v.close()
out_m.close()

In [55]:
#Import files utilities in Colab

try:
  from google.colab import files
except ImportError:
  pass

#download the files 
else:
  files.download('vecs.tsv')
  files.download('meta.tsv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>